[package]
name = "particles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cushy = "0.2.0"
rand = "0.8.5"
itertools = "0.12.1"
